vich_uploader:
    db_driver: orm
    metadata:
        type: "'attribute'"

    mappings:
        jobs_news_images:
            uri_prefix: /images/jobs_news
            upload_destination: '%kernel.project_dir%/public/images/jobs_news'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
