index:
    path: /
    controller: App\Controller\DefaultController::index
    prefix: /{_locale<%app.supported_locales%>}
    requirements:
      _locale: '%app.supported_locales%'
    defaults:
      _locale: 'de'
